In [47]:
import numpy as np
np.random.seed(42)
x=np.random.rand(100,3)
b=np.array([1,4.5,6])

In [48]:
y=x.dot(b)
x.reshape(1,-1)
y.reshape(1,-1)

array([[ 9.04471815,  2.23670949,  7.56256634,  6.62016192,  2.87891844,
         4.70103319,  5.41359352,  3.65231584,  5.1874045 ,  3.45880247,
         1.76521297, 10.14461377,  4.84953644,  3.96038601,  5.67901022,
         5.18563025,  7.1960631 , 10.37184216,  5.27728905,  2.35148765,
         6.58217299,  4.87713512,  4.1981145 ,  5.65428249,  7.91624261,
         4.64399164,  6.05849705,  2.49368934,  6.15194434,  7.46330436,
         7.89390608,  6.99340309,  2.59918217,  4.06778523,  8.04832293,
         6.62932221,  2.31371648,  9.193583  ,  9.37700887,  7.439139  ,
         6.74787185,  3.69840689,  4.73301517,  3.72174368,  7.29659186,
         6.87587448, 10.51133274,  4.29467043,  4.10821776,  2.40621219,
         2.85566363,  6.37721143,  5.52524908,  6.17707543,  3.58625441,
         3.39792385,  6.76517956,  3.67998124,  5.57544815,  5.42714596,
         6.39985891,  5.99798095,  6.49352932,  6.04410929,  5.78355336,
         8.99867169,  8.24871626,  6.20279431,  1.2

In [49]:
from sklearn.linear_model import LinearRegression

In [50]:
lr=LinearRegression()

In [74]:
m,d=x.shape
d

3

In [55]:
lr.coef_

array([1. , 4.5, 6. ])

In [61]:
class LR():
    def __init__(self):
        self.w=None
    def fit(self,x,y):
        self.w=np.linalg.inv(x.T.dot(x)).dot(x.T.dot(y))
    def predict(self,x):
        y=x.dot(self.w)
        return y

In [63]:
lr=LR()
lr.fit(x,y)
x_test = np.array([2,4,5]).reshape(1,-1)
lr.predict(x_test)
lr.w

array([1. , 4.5, 6. ])

In [101]:
class LR_GR():
    def __init__(self):
        self.w=None
    def fit(self,X,y,rate=0.02):
        y=y.reshape(-1,1)
        [n,m]=X.shape
        self.w=np.zeros((m))
        loss=1e-10
        tol=1e-5
        while tol>loss:
            h_f = X.dot(self.w).reshape(-1,1) 
            theta = self.w + rate*np.mean(X*(y - h_f),axis=0) #计算迭代的参数值
            tol = np.sum(np.abs(theta - self.w))
            self.w = theta
        

In [95]:
class LR_GD():
    def __init__(self):
        self.w = None     
    def fit(self,X,y,alpha=0.02,loss = 1e-10): # 设定步长为0.002,判断是否收敛的条件为1e-10
        y = y.reshape(-1,1) #重塑y值的维度以便矩阵运算
        [m,d] = np.shape(X) #自变量的维度
        self.w = np.zeros((d)) #将参数的初始值定为0
        tol = 1e5
        #============================= show me your code =======================
        while tol > loss:
            h_f = X.dot(self.w).reshape(-1,1) 
            theta = self.w + alpha*np.mean(X*(y - h_f),axis=0) #计算迭代的参数值
            tol = np.sum(np.abs(theta - self.w))
            self.w = theta
        #============================= show me your code =======================
    def predict(self, X):
        # 用已经拟合的参数值预测新自变量
        y_pred = X.dot(self.w)
        return y_pred  

In [102]:
lr=LR_GR()

In [103]:
lr.fit(x,y)

In [104]:
lr.w

array([1.00000003, 4.49999998, 5.99999999])